apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: yousefshabaneg/auth
      context: auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yousefshabaneg/ticketing-client
      context: client
      sync:
        manual:
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yousefshabaneg/tickets
      context: tickets
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yousefshabaneg/orders
      context: orders
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yousefshabaneg/expiration
      context: expiration
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yousefshabaneg/payments
      context: payments
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
