name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd client
          docker build -t yousefshabaneg/client .
      - run: |
          $securePass = ConvertTo-SecureString "${{ secrets.DOCKER_PASSWORD }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential("${{ secrets.DOCKER_USERNAME }}", $securePass)
          docker login -u $creds.UserName -p $creds.GetNetworkCredential().Password
        shell: powershell
      - run: docker push yousefshabaneg/client
      - run: docker logout
      - run: kubectl config use-context minikube
      - run: kubectl rollout restart deployment client-depl
