name: deploy-orders

on:
  push:
    branches:
      - main
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: Set-Location orders; docker build -t yousefshabaneg/orders .
        shell: pwsh
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push yousefshabaneg/orders
      - run: docker logout
      - run: kubectl config use-context minikube
      - run: kubectl rollout restart deployment orders-depl
