name: deploy-payments

on:
  push:
    branches:
      - main
    paths:
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd payments && docker build -t yousefshabaneg/payments .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push yousefshabaneg/payments
      - run: docker logout
      - run: kubectl config use-context minikube
      - run: kubectl rollout restart deployment payments-depl
