name: deploy-payments

on:
  push:
    branches:
      - main
    paths:
      - "payments/**"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd payments
          docker build -t yousefshabaneg/payments .
      - run: echo $env:DOCKER_PASSWORD | docker login -u $env:DOCKER_USERNAME --password-stdin
        shell: powershell
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push yousefshabaneg/payments
      - run: docker logout
      - run: kubectl config use-context minikube
      - run: kubectl rollout restart deployment payments-depl
