name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Minikube context
        run: |
          kubectl config use-context minikube

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f infra/k8s
