name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd client
          docker build -t yousefshabaneg/client .
      - run: echo $env:DOCKER_PASSWORD | docker login -u $env:DOCKER_USERNAME --password-stdin
        shell: pwsh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push yousefshabaneg/client
      - run: docker logout
      - run: kubectl config use-context minikube
      - run: kubectl rollout restart deployment client-depl
