name: deploy-tickets

on:
  push:
    branches:
      - main
    paths:
      - "tickets/**"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd tickets
          docker build -t yousefshabaneg/tickets .
      - run: echo $env:DOCKER_PASSWORD | docker login -u $env:DOCKER_USERNAME --password-stdin
        shell: powershell
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push yousefshabaneg/tickets
      - run: docker logout
      - run: kubectl config use-context minikube
      - run: kubectl rollout restart deployment tickets-depl
