name: tests-payments

on:
  pull_request:
    paths:
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd payments && npm install && npm run test:ci
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_TEST_KEY }}
